import Navbar from './NavBar/NavBar'
import Nav from './component/Nav'
import Provider from './component/Provider'
import SignIn from './component/SignIn'
import './globals.css'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider>
          <div className='main'>
            <div className='gradient' />
          </div>
          <main className='app'>
            {/* <Navbar/> */}
            <Nav/>
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
